import os
import streamlit as st

os.environ["CREWAI_TELEMETRY_OPT_OUT"] = "true"

from crew import run_analysis, get_company_name


# Page configuration
st.set_page_config(
    page_title="A-FIN: Investment Research",
    page_icon="📊",
    layout="wide"
)

# Custom CSS for a cleaner look
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1E3A5F;
        text-align: center;
        margin-bottom: 0;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #666;
        text-align: center;
        margin-top: 0;
    }
    .stButton > button {
        width: 100%;
        background-color: #1E3A5F;
        color: white;
    }
    .recommendation-box {
        padding: 20px;
        border-radius: 10px;
        margin: 20px 0;
    }
    </style>
""", unsafe_allow_html=True)

# Header
st.markdown('<p class="main-header">📊 A-FIN</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Autonomous Financial Information Nexus</p>', unsafe_allow_html=True)
st.markdown("---")

# Brief explanation
st.markdown("""
**Welcome to A-FIN!** Enter a stock ticker below, and our team of AI analysts will research the company:

- 📰 **Data Journalist** - Analyzes recent news and market sentiment
- 📈 **Quantitative Analyst** - Reviews stock metrics and technical indicators  
- 📋 **Regulatory Specialist** - Examines SEC filings and compliance
- 🎯 **Lead Analyst** - Synthesizes everything into a recommendation
""")

# Input section
col1, col2, col3 = st.columns([1, 2, 1])

with col2:
    ticker = st.text_input(
        "Enter Stock Ticker",
        placeholder="e.g., AAPL, GOOGL, MSFT",
        help="Enter a valid US stock ticker symbol"
    ).strip().upper()
    
    analyze_button = st.button("🔍 Analyze", use_container_width=True)

# Analysis section
if analyze_button:
    if not ticker:
        st.error("Please enter a stock ticker!")
    else:
        company_name = get_company_name(ticker)
        st.markdown("---")
        st.subheader(f"Analyzing: {company_name} ({ticker})")
        
        # Create a placeholder for status updates
        status_placeholder = st.empty()
        
        # Show a spinner while the crew works
        with st.spinner("🔍 Our AI analysts are researching... This may take 1-2 minutes."):
            try:
                status_placeholder.info("📰 Data Journalist is gathering news...")
                result = run_analysis(ticker)
                
                # Clear the status and show results
                status_placeholder.empty()
                
                # Display the final recommendation
                st.markdown("---")
                st.subheader("📊 Investment Recommendation")
                st.markdown(result)
                
                # Add a disclaimer
                st.markdown("---")
                st.caption("""
                ⚠️ **Disclaimer**: This analysis is generated by AI and is for educational 
                purposes only. It does not constitute financial advice. Always do your own 
                research and consult with a qualified financial advisor before making 
                investment decisions.
                """)
                
            except Exception as e:
                status_placeholder.empty()
                st.error(f"❌ An error occurred: {str(e)}")
                st.info("Please check that the ticker is valid and try again.")

# Footer
st.markdown("---")
st.markdown(
    "<p style='text-align: center; color: #999;'>Built by NR with CrewAI, Google Gemini, and ❤️</p>",
    unsafe_allow_html=True
)
